-- AlterTable
ALTER TABLE "Order" ADD COLUMN "shippingName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "shippingPhone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "addressLine1" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "addressLine2" TEXT;
ALTER TABLE "Order" ADD COLUMN "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "state" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "pincode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "deliveryNotes" TEXT;
